apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      serviceAccountName: {{ .Values.name }}
      automountServiceAccountToken: true
      containers:
      - name: code-server
        image: {{ .Values.deployment.image }}
        ports:
        - containerPort: {{ .Values.deployment.port }}
          name: code-server
        securityContext:
          privileged: true
        env:
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Values.name }}-secret
              key: password
        resources:
          limits:
            memory: 2Gi
          requests:
            memory: 2Gi
