apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}-ingress
spec:
  tls:
  - hosts:
      - code.k8s.space
    secretName: {{ .Values.name }}-tls-secret
  rules:
  - host: code.k8s.space
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.name }}-service
            port:
              number: 8080