kind: Service
apiVersion: v1
metadata:
  name: {{ .Values.name }}-service
  namespace: {{ .Values.namespace }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.name }}
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    name: {{ .Values.name }}

