# Default Values

name: "code-server"

# Kubernetes namespace
namespace: "code-server"

# Basic Authentication Username
user: "user"
# Basic Authentication Password
password: "P@ssw0rd"

# Ingress Hostname
host: code.k8s.space

service:
  type: ClusterIP

deployment:
  image: linuxserver/code-server:version-v3.10.2
  port: 8080